name: Terragrunt Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terragrunt Plan
        id: plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          TF_WORKSPACE: ${{ github.ref_name }}
        with:
          tf_version: "1.5.7"
          tg_version: "0.53.2"
          tg_command: 'run-all plan --working-dir ./environment/${{ github.ref_name }}'

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        uses: gruntwork-io/terragrunt-action@v2
        env:
          TF_WORKSPACE: ${{ github.ref_name }}
        with:
          tf_version: "1.5.7"
          tg_version: "0.53.2"
          tg_command: 'run-all apply --non-interactive --working-dir ./environment/${{ github.ref_name }}'