name: Terragrunt Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.5.7"
          tg_version: "0.53.2"
          tg_command: 'run-all apply --non-interactive --working-dir ./environment/main'